import AppKit
import Carbon.HIToolbox
import CoreGraphics
import Foundation

/// Inserts text at the current cursor. Text is inserted exactly as given (no smart leading
/// space in P1).
@MainActor
public protocol TextInserter: AnyObject {
    var name: String { get }
    func insert(_ text: String) async throws
}

public enum InsertionStrategy: String, Sendable, Equatable, Codable {
    case paste
    case unicodeTyping
    /// Remote-viewer path (Screen Sharing etc.) → `RemoteInserter`: paired receiver, else the
    /// configured typing fallback.
    case remote
}

/// Pure strategy selection by frontmost bundle ID (unit-tested).
public struct InsertionRouter: Sendable {
    public static let defaultRemoteViewerBundleIDs: Set<String> = Set(RemoteConfig.defaultViewerBundleIDs)

    public var remoteViewerBundleIDs: Set<String>
    /// Per-app overrides (e.g. an app that mishandles paste → `.unicodeTyping`).
    public var overrides: [String: InsertionStrategy]

    public init(remoteViewerBundleIDs: Set<String> = InsertionRouter.defaultRemoteViewerBundleIDs,
                overrides: [String: InsertionStrategy] = [:]) {
        self.remoteViewerBundleIDs = remoteViewerBundleIDs
        self.overrides = overrides
    }

    public func strategy(forBundleID bundleID: String?) -> InsertionStrategy {
        guard let bundleID else { return .paste }
        if let o = overrides[bundleID] { return o }
        if remoteViewerBundleIDs.contains(bundleID) { return .remote }
        return .paste
    }
}

/// Executes the router's choice. `.remote` → `remoteStrategy`, by default the P3
/// `RemoteInserter` (paired receiver over Tailscale, else the configured typing fallback).
/// Constructed WITHOUT an explicit router, the remote-viewer list is read live from
/// `RemoteConfigStore.shared` (editable in Settings → Remote Macs).
@MainActor
public final class RoutingInserter {
    private var baseRouter: InsertionRouter
    private let liveViewerIDs: (@MainActor () -> Set<String>)?
    public var router: InsertionRouter {
        get {
            var r = baseRouter
            if let live = liveViewerIDs { r.remoteViewerBundleIDs = live() }
            return r
        }
        set { baseRouter = newValue }
    }
    public let paste: TextInserter
    public let typing: TextInserter
    public var remoteStrategy: TextInserter

    public init(router: InsertionRouter? = nil, paste: TextInserter = PasteInserter(),
                typing: TextInserter = UnicodeTypingInserter(), remoteStrategy: TextInserter? = nil) {
        self.baseRouter = router ?? InsertionRouter()
        if router == nil {
            let live: @MainActor () -> Set<String> = { RemoteConfigStore.shared.config.viewerSet }
            self.liveViewerIDs = live
        } else {
            self.liveViewerIDs = nil
        }
        self.paste = paste
        self.typing = typing
        self.remoteStrategy = remoteStrategy ?? RemoteInserter()
    }

    public func inserter(forBundleID bundleID: String?) -> TextInserter {
        switch router.strategy(forBundleID: bundleID) {
        case .paste: return paste
        case .unicodeTyping: return typing
        case .remote: return remoteStrategy
        }
    }
}

/// Clipboard writes carry privacy markers; remote clipboard sync can opt out of host isolation.
@MainActor public enum PrivatePasteboard {
    public static let dictationMarker = "com.tommyyau.wisprlocal.dictation"
    public static let markerTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType"]

    @discardableResult
    public static func write(_ text: String, to pasteboard: NSPasteboard, currentHostOnly: Bool, autoGenerated: Bool = false) -> Int {
        pasteboard.prepareForNewContents(with: currentHostOnly ? .currentHostOnly : [])
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        let types = markerTypes + (autoGenerated ? ["org.nspasteboard.AutoGeneratedType", dictationMarker] : [])
        for type in types { item.setData(Data(), forType: NSPasteboard.PasteboardType(type)) }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }
}

/// A gate changed while waiting to paste; no further keystroke may be posted.
public enum PasteGateError: Error, Equatable {
    case focusChanged, secureInput
    case conflict(String)
}

/// Cancellation can leave a prefix typed; keep its count, never its text, in the outcome.
public struct TypingCancellation: Error, Sendable, Equatable {
    public var typed: Int
    public var total: Int
    public init(typed: Int, total: Int) { self.typed = typed; self.total = total }
}

/// Snapshot of every pasteboard item and every type, so we can restore it exactly.
public struct PasteboardSnapshot: Sendable {
    public var items: [[String: Data]]

    @MainActor public static func capture(_ pb: NSPasteboard) -> PasteboardSnapshot {
        let items = (pb.pasteboardItems ?? []).map { item -> [String: Data] in
            var d: [String: Data] = [:]
            for type in item.types { if let data = item.data(forType: type) { d[type.rawValue] = data } }
            return d
        }
        return PasteboardSnapshot(items: items)
    }

    @MainActor public func restore(to pb: NSPasteboard) {
        pb.clearContents()
        guard !items.isEmpty else { return }
        let objs: [NSPasteboardItem] = items.map { dict in
            let item = NSPasteboardItem()
            for (type, data) in dict { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            return item
        }
        pb.writeObjects(objs)
    }
}

/// One restore owner per pasteboard, shared by local and remote clipboard inserters.
/// Taking ownership cancels the prior task; only its exact write inherits the snapshot.
@MainActor public enum ClipboardRestore {
    private struct Pending {
        var snapshot: PasteboardSnapshot
        var task: Task<Void, Never>?
        var ourChange: Int
        var token: UUID
    }
    private static var pending: [NSPasteboard.Name: Pending] = [:]

    static func take(_ pb: NSPasteboard) -> (snapshot: PasteboardSnapshot, inherited: Int?) {
        if let previous = pending.removeValue(forKey: pb.name) {
            previous.task?.cancel()
            if pb.changeCount == previous.ourChange { return (previous.snapshot, previous.ourChange) }
        }
        return (PasteboardSnapshot.capture(pb), nil)
    }

    public static func restorePending(on pb: NSPasteboard = .general) {
        guard let value = pending.removeValue(forKey: pb.name) else { return }
        value.task?.cancel()
        if pb.changeCount == value.ourChange { value.snapshot.restore(to: pb) }
    }

    static func isPending(_ pb: NSPasteboard) -> Bool { pending[pb.name] != nil }
    static func wait(_ pb: NSPasteboard) async { await pending[pb.name]?.task?.value }

    static func hold(_ snapshot: PasteboardSnapshot, on pb: NSPasteboard, ourChange: Int) {
        pending.removeValue(forKey: pb.name)?.task?.cancel()
        pending[pb.name] = Pending(snapshot: snapshot, task: nil, ourChange: ourChange, token: UUID())
    }

    static func restoreNow(_ snapshot: PasteboardSnapshot, on pb: NSPasteboard, ourChange: Int) {
        if pb.changeCount == ourChange { snapshot.restore(to: pb) }
        if pending[pb.name]?.ourChange == ourChange {
            pending.removeValue(forKey: pb.name)?.task?.cancel()
        }
    }

    static func schedule(_ snapshot: PasteboardSnapshot, on pb: NSPasteboard, ourChange: Int,
                         delay: Duration, clock: PipelineClock) {
        // A later writer already owns the clipboard; this call must not reclaim it.
        guard pb.changeCount == ourChange else {
            restoreNow(snapshot, on: pb, ourChange: ourChange)
            return
        }
        pending.removeValue(forKey: pb.name)?.task?.cancel()
        let token = UUID(), deadline = clock.now + delay
        let task = Task { @MainActor in
            try? await clock.sleep(until: deadline)
            guard !Task.isCancelled, pending[pb.name]?.token == token else { return }
            if pb.changeCount == ourChange { snapshot.restore(to: pb) }
            pending.removeValue(forKey: pb.name)
        }
        pending[pb.name] = Pending(snapshot: snapshot, task: task, ourChange: ourChange, token: token)
    }
}

/// What happened to one paste (content-free; lands in history).
public struct InsertReport: Sendable, Equatable {
    /// Clock time the Cmd-V was posted (perceived latency ends here).
    public var postedAt: Duration
    /// true = the focused field changed after the paste (AX); false = it didn't, even after one
    /// retry; nil = could not verify (Electron/Chromium apps, AX unreadable).
    public var verified: Bool?
    /// The paste was posted a second time because the field was verifiably unchanged.
    public var retried: Bool
    /// How long the user's clipboard is held back before it is restored.
    public var restoreDelay: Duration
    /// Time spent after the first Cmd-V (verification / retry) before `insert` returned.
    public var afterPost: Duration = .zero
}

extension TextInserter {
    /// The report of the most recent `insert`, when the inserter keeps one.
    public var lastReport: InsertReport? { (self as? PasteInserter)?.lastPasteReport }
}

/// BUG C (2026-10-03, a 566-char paste into the Codex desktop app reported as inserted but
/// nothing appeared): the clipboard used to be restored a fixed 400 ms after Cmd-V, and a busy
/// Electron app may read the pasteboard later than that — and so paste the OLD clipboard, or
/// nothing. The restore now waits at least 1.5 s, longer for long text and for Electron apps,
/// is skipped if anything else wrote the clipboard meanwhile, and uses the minimum only when
/// the paste was VERIFIED (AX) to have landed.
public enum PasteRestorePolicy {
    public static let minimum: Duration = .milliseconds(1_500)
    /// Added per 1,000 characters.
    public static let perThousandChars: Duration = .seconds(1)
    /// Electron / Chromium apps read the pasteboard on their own schedule.
    public static let electronFactor = 2
    public static let maximum: Duration = .seconds(8)

    public static func delay(textLength: Int, electron: Bool, verified: Bool?) -> Duration {
        if verified == true { return minimum }
        // Whole milliseconds (exact, testable): 1 ms per character on top of the minimum.
        var ms = Int(minimum.ms) + Int(perThousandChars.ms) * max(0, textLength) / 1_000
        if electron { ms *= electronFactor }
        return min(maximum, .milliseconds(ms))
    }
}

/// Electron / Chromium-shell apps: no usable AX text, late pasteboard reads.
public enum ElectronApps {
    public static let knownBundleIDs: Set<String> = [
        "com.openai.codex", "com.anthropic.claudefordesktop", "com.openai.chat", "com.tinyspeck.slackmacgap",
        "com.microsoft.VSCode", "com.todesktop.230313mzl4w4u92", "notion.id", "com.hnc.Discord",
        "com.figma.Desktop", "md.obsidian", "com.linear", "com.spotify.client", "com.microsoft.teams2",
    ]

    /// Known bundle id, or the bundle ships Electron (`app.asar` / Electron Framework).
    public static func isElectron(bundleID: String?, bundleURL: URL?) -> Bool {
        if let bundleID, knownBundleIDs.contains(bundleID) { return true }
        guard let url = bundleURL else { return false }
        let fm = FileManager.default
        return fm.fileExists(atPath: url.appendingPathComponent("Contents/Resources/app.asar").path)
            || fm.fileExists(atPath: url.appendingPathComponent("Contents/Frameworks/Electron Framework.framework").path)
    }
}

/// The frontmost app at paste time (the focus guard has already checked it is the target).
public struct PasteTarget: Sendable, Equatable {
    public var pid: Int32
    public var bundleID: String?
    public var isElectron: Bool
    public init(pid: Int32, bundleID: String?, isElectron: Bool) { self.pid = pid; self.bundleID = bundleID; self.isElectron = isElectron }

    @MainActor public static func frontmost() -> PasteTarget? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return PasteTarget(pid: app.processIdentifier, bundleID: app.bundleIdentifier,
                           isElectron: ElectronApps.isElectron(bundleID: app.bundleIdentifier, bundleURL: app.bundleURL))
    }
}

/// Content-free state of the focused text field: counts and offsets only, never the text.
public struct FocusedFieldState: Sendable, Equatable {
    public var characterCount: Int
    public var selectionLocation: Int
    public init(characterCount: Int, selectionLocation: Int) {
        self.characterCount = characterCount; self.selectionLocation = selectionLocation
    }
}

@MainActor public protocol PasteVerifying: AnyObject {
    /// nil = not readable (no AX, Electron, no focused text element).
    func read(pid: Int32) async -> FocusedFieldState?
}

/// Reads the focused element's character count and caret offset through AX (50 ms budget),
/// on `AXQueue` (off the main actor).
@MainActor public final class AXPasteVerifier: PasteVerifying {
    public var timeout: Float = 0.05
    public init() {}
    public func read(pid: Int32) async -> FocusedFieldState? {
        let timeout = self.timeout
        return await AXQueue.run { Self.read(pid: pid, timeout: timeout) }
    }

    nonisolated static func read(pid: Int32, timeout: Float) -> FocusedFieldState? {
        guard AXIsProcessTrusted() else { return nil }
        let app = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(app, timeout)
        var ref: CFTypeRef?
        guard AXUIElementCopyAttributeValue(app, kAXFocusedUIElementAttribute as CFString, &ref) == .success,
              let ref, CFGetTypeID(ref) == AXUIElementGetTypeID() else { return nil }
        let el = ref as! AXUIElement
        AXUIElementSetMessagingTimeout(el, timeout)
        var countRef: CFTypeRef?, rangeRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(el, kAXNumberOfCharactersAttribute as CFString, &countRef) == .success,
              let count = countRef as? Int,
              AXUIElementCopyAttributeValue(el, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
              let rangeRef, CFGetTypeID(rangeRef) == AXValueGetTypeID() else { return nil }
        var r = CFRange()
        guard AXValueGetValue(rangeRef as! AXValue, .cfRange, &r) else { return nil }
        return FocusedFieldState(characterCount: count, selectionLocation: r.location)
    }
}

/// The Cmd-V keystroke. Flags are EXACTLY `.maskCommand`: no Fn/Globe (`.maskSecondaryFn`) —
/// a hands-free stop commits on 🌐-DOWN, so the key can still be physically held — and no
/// other modifier (`PasteKeystrokeTests`). A private event source, so the physical modifier
/// state is not merged into the synthetic event.
public enum PasteKeystroke {
    public static let flags: CGEventFlags = .maskCommand
    /// Physical modifiers that would turn Cmd-V into another shortcut.
    public static let conflictingModifiers: CGEventFlags = [.maskSecondaryFn, .maskShift, .maskControl, .maskAlternate]

    public static func events(key: CGKeyCode) -> [CGEvent] {
        let src = CGEventSource(stateID: .privateState)
        return [true, false].compactMap { down in
            guard let e = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: down) else { return nil }
            e.flags = flags
            e.setIntegerValueField(.eventSourceUserData, value: SyntheticEventMarker.value)
            return e
        }
    }

    @MainActor public static func post(key: CGKeyCode) throws {
        guard AXIsProcessTrusted() else { throw InsertionError.notTrusted }
        let evs = events(key: key)
        guard evs.count == 2 else { throw InsertionError.eventCreationFailed }
        for e in evs { e.post(tap: .cghidEventTap) }
    }

    /// Physical modifier state right now (hardware ∪ session).
    @MainActor public static func physicalModifiersHeld() -> Bool {
        let f = CGEventSource.flagsState(.hidSystemState).union(CGEventSource.flagsState(.combinedSessionState))
        return !f.intersection(conflictingModifiers).isEmpty
    }
}

/// Pasteboard + synthesized Cmd-V (real keycode, `PasteKeystroke`).
///
/// 1. Waits (≤ `maxModifierWait`) until 🌐 and every conflicting modifier is physically up.
/// 2. Writes the text, posts Cmd-V.
/// 3. Verifies when it can (`PasteVerifying`, skipped for Electron): if the focused field is
///    readable and unchanged `verifyDelay` later, posts Cmd-V ONCE more, then checks again.
/// 4. Restores the user's clipboard after `PasteRestorePolicy` (or the fixed `restoreDelay`
///    override), never if anything else wrote the clipboard meanwhile.
/// A dictation that pastes while a restore is still pending reuses the ORIGINAL snapshot (the
/// pending restore is cancelled), so back-to-back dictations never leave our text on the
/// clipboard. The V keycode is resolved for the current layout, see `KeyboardLayoutMap`.
@MainActor
public final class PasteInserter: TextInserter {
    public var name: String { "paste" }
    /// Fixed restore delay (tests, receiver); nil = adaptive `PasteRestorePolicy`.
    public var restoreDelay: Duration?
    public var verifyDelay: Duration = .milliseconds(300)
    public var maxModifierWait: Duration = .milliseconds(1_500)
    /// 🌐 / modifiers physically held (the app also ORs in the Globe monitor's own state).
    public var modifiersHeld: @MainActor () -> Bool
    public var target: @MainActor () -> PasteTarget?
    public var verifier: PasteVerifying?
    public var secureInputActive: @MainActor () -> Bool
    private let pasteboard: NSPasteboard
    /// Posts the paste keystroke (real Cmd-V; injectable for tests).
    private let postPaste: @MainActor () throws -> Void
    /// Time source for every wait here (tests inject a `ManualClock`).
    private let clock: PipelineClock
    public private(set) var lastPasteReport: InsertReport?

    public init(pasteboard: NSPasteboard = .general, restoreDelay: Duration? = nil,
                postPaste: (@MainActor () throws -> Void)? = nil,
                clock: PipelineClock = SystemPipelineClock(),
                verifier: PasteVerifying? = nil,
                target: (@MainActor () -> PasteTarget?)? = nil,
                modifiersHeld: (@MainActor () -> Bool)? = nil) {
        self.pasteboard = pasteboard
        self.clock = clock
        self.restoreDelay = restoreDelay
        self.verifier = verifier
        // Real keystrokes ⇒ real environment; an injected `postPaste` (tests) gets neutral defaults.
        let live = postPaste == nil
        if live { self.secureInputActive = { SystemSecureInput().isSecureInputActive } }
        else { self.secureInputActive = { false } }
        self.postPaste = postPaste ?? { try PasteKeystroke.post(key: KeyboardLayoutMap.shared.pasteKeyCode) }
        if let target { self.target = target } else if live { self.target = { PasteTarget.frontmost() } } else { self.target = { nil } }
        if let modifiersHeld { self.modifiersHeld = modifiersHeld }
        else if live { self.modifiersHeld = { PasteKeystroke.physicalModifiersHeld() } } else { self.modifiersHeld = { false } }
        if live && verifier == nil { self.verifier = AXPasteVerifier() }
    }

    private var inserting = false
    private var insertWaiters: [CheckedContinuation<Void, Never>] = []

    private func acquireInsert() async {
        if inserting {
            await withCheckedContinuation { insertWaiters.append($0) }
        } else {
            inserting = true
        }
    }

    private func releaseInsert() {
        if insertWaiters.isEmpty { inserting = false }
        else { insertWaiters.removeFirst().resume() }
    }

    private var holdsGeneratedText: Bool {
        pasteboard.types?.contains(NSPasteboard.PasteboardType(PrivatePasteboard.dictationMarker)) == true
    }

    /// True while a clipboard restore is scheduled (tests).
    public var restorePending: Bool { ClipboardRestore.isPending(pasteboard) }

    /// Cancelling the calling task (Esc / triple-tap, R1) before Cmd-V is posted throws
    /// `CancellationError` and pastes nothing; after it is posted, verification and the retry
    /// are skipped (a second Cmd-V after a cancel would be a new action).
    public func insert(_ text: String) async throws {
        try await insert(text, prePostCheck: nil)
    }

    /// Gates belong to this call, including when queued behind another paste.
    public func insert(_ text: String, prePostCheck: (@MainActor () throws -> Void)?) async throws {
        guard !text.isEmpty else { return }
        await acquireInsert()
        defer { releaseInsert() }
        try Task.checkCancellation()
        lastPasteReport = nil
        let ownership = ClipboardRestore.take(pasteboard)
        var snapshot = ownership.snapshot
        let inherited = ownership.inherited
        let snapshotChange = pasteboard.changeCount
        /// Cancelled before anything was pasted: the user's clipboard comes back as it would have.
        func abandon() -> CancellationError {
            if let inherited, pasteboard.changeCount == inherited { snapshot.restore(to: pasteboard) }
            return CancellationError()
        }
        let tgt = target()
        let electron = tgt?.isElectron ?? false
        // Field state BEFORE (content-free), only where AX is meaningful.
        var before: FocusedFieldState?
        if !electron, let tgt, let verifier { before = await verifier.read(pid: tgt.pid) }
        if Task.isCancelled { throw abandon() }

        // Clean modifier state: wait for 🌐 (hands-free stop commits on key-DOWN) and any
        // modifier that would turn Cmd-V into something else.
        let waitUntil = clock.now + maxModifierWait
        while modifiersHeld(), clock.now < waitUntil {
            if Task.isCancelled { throw abandon() }
            try? await clock.sleep(until: min(waitUntil, clock.now + .milliseconds(20)))
        }
        if Task.isCancelled { throw abandon() }

        func checkGates() throws {
            try Task.checkCancellation()
            try prePostCheck?()
            if secureInputActive() { throw PasteGateError.secureInput }
            if target() != tgt { throw PasteGateError.focusChanged }
        }
        do { try checkGates() } catch {
            if let inherited, pasteboard.changeCount == inherited { snapshot.restore(to: pasteboard) }
            throw error
        }
        if ClipboardRestore.isPending(pasteboard) {
            // Another inserter may have written while we waited for modifiers / AX.
            snapshot = ClipboardRestore.take(pasteboard).snapshot
        } else if pasteboard.changeCount != snapshotChange, !holdsGeneratedText {
            snapshot = PasteboardSnapshot.capture(pasteboard)
        }
        let ourChange = write(text)
        ClipboardRestore.hold(snapshot, on: pasteboard, ourChange: ourChange)
        do { try postPaste() } catch {
            ClipboardRestore.restoreNow(snapshot, on: pasteboard, ourChange: ourChange)
            throw error
        }
        let postedAt = clock.now
        var verified: Bool?
        var retried = false
        if let before, let tgt, let verifier, !Task.isCancelled {
            try? await clock.sleep(until: clock.now + verifyDelay)
            var after = Task.isCancelled ? nil : await verifier.read(pid: tgt.pid)
            if after == before, !Task.isCancelled, pasteboard.changeCount == ourChange {
                // Verifiably unchanged: paste once more (our text must still be on the clipboard).
                var retryAllowed = true
                do { try checkGates() } catch { retryAllowed = false }
                if retryAllowed {
                    do {
                        try postPaste()
                        retried = true
                    } catch {
                        Log.warning("paste: retry keystroke failed")
                    }
                    if retried { Log.info("paste: field unchanged after \(Int(verifyDelay.ms)) ms; retried once") }
                    try? await clock.sleep(until: clock.now + verifyDelay)
                    after = await verifier.read(pid: tgt.pid)
                }
            }
            verified = after.map { $0 != before }
        }
        let delay = restoreDelay ?? PasteRestorePolicy.delay(textLength: text.count, electron: electron, verified: verified)
        lastPasteReport = InsertReport(postedAt: postedAt, verified: verified, retried: retried, restoreDelay: delay,
                                       afterPost: clock.now - postedAt)
        scheduleRestore(snapshot, ourChange: ourChange, delay: delay)
    }

    /// Our temporary clipboard write; returns its changeCount.
    private func write(_ text: String) -> Int {
        PrivatePasteboard.write(text, to: pasteboard, currentHostOnly: true, autoGenerated: true)
    }

    private func scheduleRestore(_ snapshot: PasteboardSnapshot, ourChange: Int, delay: Duration) {
        ClipboardRestore.schedule(snapshot, on: pasteboard, ourChange: ourChange, delay: delay, clock: clock)
    }

    /// Await the shared scheduled restore (tests).
    public func waitForRestore() async { await ClipboardRestore.wait(pasteboard) }
}

extension Duration {
    var ms: Double { Double(components.seconds) * 1000 + Double(components.attoseconds) / 1e15 }
}

/// Fallback: types the text as Unicode key events (newline → Return keycode).
@MainActor
public final class UnicodeTypingInserter: TextInserter {
    public var name: String { "unicode" }
    public var interKeyDelay: Duration = .milliseconds(2)
    private let post: @MainActor (Step) throws -> Void
    public convenience init() { self.init(post: nil) }
    public init(post: (@MainActor (Step) throws -> Void)?) {
        self.post = post ?? { step in
            switch step {
            case .unicode(let chunk): try KeyEventPoster.postUnicode(chunk)
            case .key(let code, let shift): try KeyEventPoster.postKey(CGKeyCode(code), flags: shift ? [.maskShift] : [])
            }
        }
    }

    /// One synthesized keyboard action.
    public enum Step: Equatable, Sendable {
        case unicode([UInt16])
        case key(code: UInt16, shift: Bool)
    }

    /// SAFETY: a newline is typed as **Shift+Return**, never a bare Return — in chat apps (Slack,
    /// Messages, Teams…) a bare Return SENDS the message. Shift+Return inserts a line break in
    /// those apps and in ordinary text views. Pure, so it is unit-tested.
    nonisolated public static func plan(_ text: String) -> [Step] {
        var steps: [Step] = []
        let lines = text.replacingOccurrences(of: "\r\n", with: "\n").replacingOccurrences(of: "\r", with: "\n")
            .components(separatedBy: "\n")
        for (i, line) in lines.enumerated() {
            let utf16 = Array(line.utf16)
            var idx = 0
            while idx < utf16.count {
                steps.append(.unicode(Array(utf16[idx..<min(idx + 20, utf16.count)])))
                idx += 20
            }
            if i < lines.count - 1 { steps.append(.key(code: UInt16(kVK_Return), shift: true)) }
        }
        return steps
    }

    public func insert(_ text: String) async throws {
        var typed = 0
        for step in Self.plan(text) {
            if Task.isCancelled { throw TypingCancellation(typed: typed, total: text.count) }
            try post(step)
            switch step {
            case .unicode(let chunk): typed += String(decoding: chunk, as: UTF16.self).count
            case .key: typed += 1
            }
            do { try await Task.sleep(for: interKeyDelay) }
            catch { throw TypingCancellation(typed: typed, total: text.count) }
            if Task.isCancelled { throw TypingCancellation(typed: typed, total: text.count) }
        }
    }
}

public enum InsertionError: Error, LocalizedError {
    case eventCreationFailed
    case notTrusted
    public var errorDescription: String? {
        switch self {
        case .eventCreationFailed: return "Could not synthesize keyboard events"
        case .notTrusted: return "Accessibility permission is required to insert text"
        }
    }
}

enum KeyEventPoster {
    static func postKey(_ key: CGKeyCode, flags: CGEventFlags) throws {
        guard AXIsProcessTrusted() else { throw InsertionError.notTrusted }
        let src = CGEventSource(stateID: .hidSystemState)
        guard let down = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: true),
              let up = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: false) else {
            throw InsertionError.eventCreationFailed
        }
        for e in [down, up] {
            e.flags = flags
            e.setIntegerValueField(.eventSourceUserData, value: SyntheticEventMarker.value)
        }
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
    }

    static func postUnicode(_ utf16: [UniChar]) throws {
        guard AXIsProcessTrusted() else { throw InsertionError.notTrusted }
        let src = CGEventSource(stateID: .hidSystemState)
        guard let down = CGEvent(keyboardEventSource: src, virtualKey: 0, keyDown: true),
              let up = CGEvent(keyboardEventSource: src, virtualKey: 0, keyDown: false) else {
            throw InsertionError.eventCreationFailed
        }
        for e in [down, up] {
            e.flags = []
            e.setIntegerValueField(.eventSourceUserData, value: SyntheticEventMarker.value)
            utf16.withUnsafeBufferPointer { e.keyboardSetUnicodeString(stringLength: $0.count, unicodeString: $0.baseAddress) }
        }
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
    }
}

/// Global "paste the last dictation again" shortcut: ⌃⌥⌘V. Chosen to avoid ⌘⇧V (Paste and Match
/// Style in most apps) and ⌥⌘V (Finder's Move, Paste Style in Office). Handled in the Globe
/// event tap, which consumes only this exact chord.
public enum PasteAgainShortcut {
    public static let display = "⌃⌥⌘V"
    public static let required: CGEventFlags = [.maskControl, .maskAlternate, .maskCommand]
    static let checked: CGEventFlags = [.maskControl, .maskAlternate, .maskCommand, .maskShift]

    public static func matches(keyCode: Int64, flags: CGEventFlags, pasteKeyCode: CGKeyCode) -> Bool {
        keyCode == Int64(pasteKeyCode) && flags.intersection(checked) == required
    }
}
